name: Build and Deploy Demo

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install

    - name: Build library
      run: pnpm build

    - name: Build demo for GitHub Pages
      run: |
        # 先构建库
        pnpm build
        
        # 使用统一配置构建 demo
        pnpm build:demo
        
        # 处理 GitHub Pages 路径问题
        # 替换 HTML 中的 iconset.svg 路径（object 标签）
        sed -i 's|data="/iconset\.svg"|data="/SVG-Morpheus-ts/iconset.svg"|g' dist-demo/index.html
        
        # 替换 JavaScript 中的 vite.svg 路径（bundleSvgs 中使用）
        sed -i "s|'/vite\.svg'|'/SVG-Morpheus-ts/vite.svg'|g" dist-demo/*.js
        
        # 替换代码示例中的 iconset.svg 路径（用于显示正确的示例代码）
        sed -i 's|<object data="/iconset\.svg"|<object data="/SVG-Morpheus-ts/iconset.svg"|g' dist-demo/index.html
        
        # 验证文件结构
        echo "构建输出文件:"
        ls -la dist-demo/

    - name: Setup Pages
      uses: actions/configure-pages@v4
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        path: './dist-demo'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 